### ISSUE TITLE
Ошибка именования, City.cs

### ISSUE THREAD

**Issue by ElKoriano** [80974397321/EuroDiffusion#1]
Свойство country с маленькой буквы
https://github.com/80974397321/EuroDiffusion/blob/bcde1608fcc2854d27cd9fbdcb20c310544b4534/City.cs#L12

**Comment by 80974397321** [comment]
Исправлено
https://github.com/80974397321/EuroDiffusion/blob/cc36a1153e0a0a0f737bbad8ad7ba16e353741f1/City.cs#L12
