### ISSUE TITLE
Лишние(?) переходы строк

### ISSUE THREAD

**Issue by ElKoriano** [80974397321/EuroDiffusion#2]
Нужно ли столько лишних переходов на новую строку в main?
https://github.com/80974397321/EuroDiffusion/blob/bcde1608fcc2854d27cd9fbdcb20c310544b4534/Program.cs#L11-L14
Так же есть конструктор в EuroDef где нет кода, но есть переходы (Зачем)
https://github.com/80974397321/EuroDiffusion/blob/bcde1608fcc2854d27cd9fbdcb20c310544b4534/EuroDiffusion.cs#L12-L15

**Comment by 80974397321** [comment]
Разрывы строк в main() отделяют логические части решения: объявления, ввод, обработка, вывод. Кое-где убрал лишние разрывы.
Конструктор без разрыва очень плохо смотрится в редакторе, визуально кажется, что чего-то не хватает, такое оформление просто приятнее смотрится
