### ISSUE TITLE
Непонятное именование

### ISSUE THREAD

**Issue by ElKoriano** [80974397321/EuroDiffusion#3]
Intersect в EuroDiffusion имеет название полей и параметров которые не совсем интуитивно-понятны (возможно стоит a1->x1, b1->y1 etc)
https://github.com/80974397321/EuroDiffusion/blob/bcde1608fcc2854d27cd9fbdcb20c310544b4534/EuroDiffusion.cs#L136
Аналогично в City/Read поле n

**Comment by 80974397321** [comment]
Исправлено
https://github.com/80974397321/EuroDiffusion/blob/cc36a1153e0a0a0f737bbad8ad7ba16e353741f1/EuroDiffusion.cs#L127

В Case.Read переменная n - временная для преобразования данных, не имеет важного практического назначения и используется однообразно только непосредственно рядом с объявлением, поэтому не вижу смысла ее переименовывать и даже не очень понимаю как
