### ISSUE TITLE
Непонятное именование 

### ISSUE THREAD

**Issue by ElKoriano** [80974397321/EuroDiffusion#4]
EuroDiffusion функция DoSolve
https://github.com/80974397321/EuroDiffusion/blob/bcde1608fcc2854d27cd9fbdcb20c310544b4534/EuroDiffusion.cs#L163
Возможно стоит выбрать другое, более понятное и красивое название?
Также название Tick, Share, ApplyDelta - стоит развернуть названия, так как непонятно из названия назначение функций

**Comment by 80974397321** [comment]
Исправлено.
https://github.com/80974397321/EuroDiffusion/blob/cc36a1153e0a0a0f737bbad8ad7ba16e353741f1/EuroDiffusion.cs#L131
https://github.com/80974397321/EuroDiffusion/blob/cc36a1153e0a0a0f737bbad8ad7ba16e353741f1/EuroDiffusion.cs#L185
https://github.com/80974397321/EuroDiffusion/blob/cc36a1153e0a0a0f737bbad8ad7ba16e353741f1/EuroDiffusion.cs#L193
https://github.com/80974397321/EuroDiffusion/blob/cc36a1153e0a0a0f737bbad8ad7ba16e353741f1/EuroDiffusion.cs#L206
