### ISSUE TITLE
Shall be initialized?

### ISSUE THREAD

**Issue by IanaKhitsko** [80974397321/EuroDiffusion#5]
https://github.com/80974397321/EuroDiffusion/blob/bcde1608fcc2854d27cd9fbdcb20c310544b4534/Case.cs#L18

Uninitialized variable

**Comment by 80974397321** [comment]
Use of uninitialized variable produces compile-time error, thus code would not work.
Later it is used as **out** parameter where it obtains value, so preemptive initialization is not necessery and has no meaning.

https://github.com/80974397321/EuroDiffusion/blob/cc36a1153e0a0a0f737bbad8ad7ba16e353741f1/Case.cs#L22
