### ISSUE TITLE
Return value

### ISSUE THREAD

**Issue by IanaKhitsko** [80974397321/EuroDiffusion#6]
https://github.com/80974397321/EuroDiffusion/blob/bcde1608fcc2854d27cd9fbdcb20c310544b4534/EuroDiffusion.cs#L124

if (c1.Name == c2.Name)
            {
                result = false;
            }
return ((c1.Xl == c2.Xh + 1 && Intersect(c1.Yl, c1.Yh, c2.Yl, c2.Yh)) ||
                     (c1.Xh == c2.Xl - 1 && Intersect(c1.Yl, c1.Yh, c2.Yl, c2.Yh)) ||
                     (c1.Yl == c2.Yh + 1 && Intersect(c1.Xl, c1.Xh, c2.Xl, c2.Xh)) ||
                     (c1.Yh == c2.Yl - 1 && Intersect(c1.Xl, c1.Xh, c2.Xl, c2.Xh)));

**Comment by 80974397321** [comment]
Simplified into one complex condition.
https://github.com/80974397321/EuroDiffusion/blob/cc36a1153e0a0a0f737bbad8ad7ba16e353741f1/EuroDiffusion.cs#L119-L126
