### ISSUE TITLE
Unused values

### ISSUE THREAD

**Issue by IanaKhitsko** [80974397321/EuroDiffusion#7]
https://github.com/80974397321/EuroDiffusion/blob/bcde1608fcc2854d27cd9fbdcb20c310544b4534/EuroDiffusion.cs#L140

aFirst and bSecond are not used. Maybe some conditions are missed?
Otherwise functions just checks for   (a1 <= a2) ? a2 <= b1 : a1 <= b2;

**Comment by 80974397321** [comment]
Agree, function does exactly that and it is supposed bahaviour.
Fixed.
https://github.com/80974397321/EuroDiffusion/blob/cc36a1153e0a0a0f737bbad8ad7ba16e353741f1/EuroDiffusion.cs#L127-L130
