### ISSUE TITLE
Introduce const

### ISSUE THREAD

**Issue by IanaKhitsko** [80974397321/EuroDiffusion#8]
https://github.com/80974397321/EuroDiffusion/blob/bcde1608fcc2854d27cd9fbdcb20c310544b4534/EuroDiffusion.cs#L221

Please introduce const for 1000

**Comment by 80974397321** [comment]
Fixed
https://github.com/80974397321/EuroDiffusion/blob/cc36a1153e0a0a0f737bbad8ad7ba16e353741f1/EuroDiffusion.cs#L11
